FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@10.17.1 --activate

WORKDIR /app

# Copia manifestos para cache de dependências
COPY ../../package.json ../../pnpm-lock.yaml ../../pnpm-workspace.yaml ../../turbo.json ./
COPY package.json ./apps/client/package.json

RUN pnpm install --frozen-lockfile

# Copia o restante do código do client
COPY . ./apps/client

WORKDIR /app/apps/client

EXPOSE 4321

CMD ["pnpm", "dev", "--", "--host", "0.0.0.0"]


